Todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('todolist/', views.todolist, name='todolist'),
    path('deleteitem/<int:todoID>', views.deleteitem, name='deletetodo')
]

todoapp/models.py
from django.db import models, connection
from datetime import datetime

def getmonthday():
    current = datetime.now()
    return f"{current.strftime('%B')}, {current.day} | {current.hour}:{current.minute} "

# Create your models here.
class todolist(models.Model):
    todo = models.CharField(max_length=100)
    priority = models.BooleanField(default=False)
    created = models.CharField(max_length=50, default = getmonthday)

    def __str__(self) -> str:
        return f'{self.todo} ==== {self.priority}'


def truncate_cars():
    with connection.cursor() as cursor:
        table_name = todolist._meta.db_table
        cursor.execute(f'DELETE FROM {table_name};')
        cursor.execute(f'VACUUM;')

todoapp/forms.py
from django import forms
from .models import todolist
from django.forms import ModelForm


# class AddToDo(forms.Form):
#     todo = forms.CharField(label='ToDo:',
#                            max_length=100,
#                            required=False,
#                            widget=forms.TextInput(attrs={'class':'form-control'})
#                            )
#     priority = forms.BooleanField(label='is this important?',
#                                   required=False,
#                                   widget=forms.CheckboxInput()
#                                 )
class AddToDo(ModelForm):
    class Meta:
        model = todolist
        fields = ['todo', 'priority'] # or i can use "__all__" if all

        labels = {
            'todo':'Todo',
            'priority': 'is this important?'
        }

        widgets = {
            'todo': forms.TextInput(attrs={'class':'form-control'}),
        }

        # error_messages = {
        # }

todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
from .forms import AddToDo

# Create your views here.

def home(request):
    return render(request,'todoapp/index.html')


def deleteitem(request, todoID):
    item = models.todolist.objects.get(pk=todoID)
    item.delete()
    return redirect('todoapp:todolist')

def todolist(request):

    if request.method == 'POST':
        addform = AddToDo(request.POST)
        try:
            if addform.is_valid():
                # todo = addform.cleaned_data['todo']
                # priority = addform.cleaned_data['priority']
                # models.todolist.objects.create(todo=todo, priority=priority)
                addform.save()
                return redirect('todoapp:todolist')
        except Exception as e:
            print(f'error {e}')
    else:
        addform = AddToDo()    
    todos = models.todolist.objects.all().order_by('-priority')
    return render(request, 'todoapp/todolist.html', context={'todos': todos, 'addform':addform})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> {% block title %} default title{% endblock title %} default title </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static "todoapp/style.css" %}">
        <link rel="stylesheet" href="{% static "todoapp/animation.css" %}">
    </head>
    <body style='background-color: #F2EAD3'>
        {% comment %} nav here  {% endcomment %}
        
        {% block content %}
        {% endblock content %}

    </body>
</html>

todoapp/templates/todoapp/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class='homecontainer'>
    <div id='home-intro'>
        <h1>Sticky Notes</h1>
            <p>Elevate your productivity with our digital sticky notes.
            Mark tasks as important, stay on top of your priorities,
            and transform the way you organize your day. Simple, effective,
            and always at your fingertips</p>
            <a href='{% url "todoapp:todolist" %}'>
                <button type="button" class="btn-color">ToDo List</button>
            </a>
    </div>
    <div id='home-img'>
        <img src="{% static "todoapp/images/pngsee.png" %}" class="rounded mx-auto d-block" alt="...">
    </div>
</div>


{% endblock content %}

todoapp/templates/todoapp/todolist.html
{% extends "base.html" %}

{% block title %}Todo List{% endblock title %}

{% block content %}
<div class='container'>
    <div class='todolist'>
        <div class='todocomponents' id='addutil'>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="title">
                    <h2 class="mb-4"> Add Sticky Notes</h2>
                </div>
                <div class="mb-3">
                    {{addform.todo.label_tag}}
                    {{addform.todo}}
                    {{addform.todo.errors}}
                </div>
                <div class="mb-3">
                    <div class="form-check">
                    {{addform.priority}}{{addform.priority.label_tag}}
                    </div>
                </div>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <button type="submit" class="btn-color"><strong>ADD</strong></button>
                </div>
            </form>
        </div>
        <div class='todocomponents' id='list'>
            <div class="title">
                <h3>Sticky wall</h3> 
            </div>
            <div class="stickerwall">
                {% for item in todos %}
                    <div class="sticker" >
                        <h4 class="sticker-title">{{item.todo}}{% if item.priority %}
                                                                <i class="fa-solid fa-star"></i>
                                                                {% else %} 
                                                                <i class="fa-regular fa-star"></i>
                                                                {% endif %} </i></h4>
                    <div class='metadata' style='display:flex; justify-content: space-between;'>
                        <div id='timecreated'>
                            <p><i>{{item.created}}</i></p>
                        </div>
                        <div id="trash">
                           <a class='removeitem' href='{% url "todoapp:deletetodo" item.id %}'>
                            <i class="fa-solid fa-trash" id='removelogo'></i>
                            </a>
                        </div>
                    </div>
                    </div>
                {% endfor %} 
                
            </div>
        </div>
    </div>
</div>
<script>
document.getElementById('additemform').addEventListener('submit', function () {
    // Clear the form fields after submission
    this.reset();
});
</script>
{% endblock content %}